#!/bin/sh
set -e

CUDA_HOME=/usr/local/cuda
export CUDACXX=$CUDA_HOME/bin/nvcc
export OPENSSL_ROOT_DIR=$HOME/local/openssl

build_flags() {
    # echo -e cpu
    echo -e gpu
}

reinstall() {
    ./build.sh $(build_flags)
    # python3.7 -m pip install -U output/mindspore-1.0.0-cp37-cp37m-linux_x86_64.whl
    python3.7 -m pip install -U output/mindspore_gpu-1.0.0-cp37-cp37m-linux_x86_64.whl
}

reinstall
