#!/bin/sh
set -e

reinstall() {
    # python3.7 -m pip install -U output/mindspore-1.0.0-cp37-cp37m-linux_x86_64.whl
    python3.7 -m pip install -U output/mindspore_gpu-1.0.0-cp37-cp37m-linux_x86_64.whl
}

reinstall
